name: Static Analysis Checks

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Run static analysis checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run static analysis checks
        run: ./gradlew checkFormat --daemon
